name: Time-Series-Simulation
channels:
  - https://pypi.tuna.tsinghua.edu.cn/simple
dependencies:
  - numpy
  - matplotlib
  - pandas
  - ipywidgets
  - typing
  - datetime
  - IPython
  - warning
  - time
  - chinese_calender