name: Time-Series-Simulation
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - matplotlib
  - pandas
  - ipywidgets
  - typing
  - pip:
      - chinesecalendar
      - datetime
      - IPython
      - warning
      - time
