name: Time-Series-Simulation
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - matplotlib
  - pandas
  - ipywidgets
  - typing
  - datetime
  - IPython
  - warning
  - time
  - pip:
     - chinesecalendar
